# This script runs 100k simulations on each scenario
# and compares the number of accidents from baseline to post implementation
# from there a large plot is generated showing how often the implementation
# showed a decrease/increase/no change in accidents vs the baseline
# This gives us a complicated, though useful way, to show how much of an impact
# these implementations are likely to have. 


library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)

df <- readr::read_csv("data/results_2026-04-19.csv", show_col_types = FALSE)

set.seed(100)

trials <- 100000
years <- 10
# Wow really should've made a helper function for this but whatever
sims_4th_base <- rpois(trials, lambda=df[1,]$pred_ped * years)
sims_4th_post_cmf <- rpois(trials, lambda=df[2,]$pred_ped * years)
sims_4th_post_spf <- rpois(trials, lambda=df[3,]$pred_ped * years)
sims_mesa_base_low <- rpois(trials, lambda=df[4,]$pred_ped * years)
sims_mesa_base_high <- rpois(trials, lambda=df[5,]$pred_ped * years)
sims_mesa_post_low <- rpois(trials, lambda=df[6,]$pred_ped * years)
sims_mesa_post_high <- rpois(trials, lambda=df[7,]$pred_ped * years)
delta_4th_vs_cmf <- sims_4th_base - sims_4th_post_cmf
delta_4th_vs_spf <- sims_4th_base - sims_4th_post_spf
delta_mesa_low <- sims_mesa_base_low - sims_mesa_post_low
delta_mesa_high <- sims_mesa_base_high - sims_mesa_post_high

# Below code generated by chatgpt
df_all <- bind_rows(
  data.frame(delta = delta_4th_vs_cmf,  scenario = "4th: Baseline vs CMF"),
  data.frame(delta = delta_4th_vs_spf,  scenario = "4th: Baseline vs SPF"),
  data.frame(delta = delta_mesa_low, scenario = "Mesa Low: Before vs After"),
  data.frame(delta = delta_mesa_high,scenario = "Mesa High: Before vs After")
) %>%
  mutate(
    outcome = case_when(
      delta > 0  ~ "Improvement",
      delta == 0 ~ "No difference",
      delta < 0  ~ "Worse"
    )
  )

df_pmf <- df_all %>%
  group_by(scenario, delta, outcome) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(scenario) %>%
  mutate(prob = n / sum(n))

df_stats <- df_all %>%
  group_by(scenario) %>%
  summarise(
    p_improve = mean(delta > 0),
    p_same    = mean(delta == 0),
    p_worse   = mean(delta < 0),
    x_pos     = quantile(delta, 0.75),
    .groups = "drop"
  )

p <- ggplot(df_pmf, aes(x = delta, y = prob, fill = outcome)) +
  geom_col(width = 0.9) +
  
  scale_fill_manual(values = c(
    "Improvement"   = "forestgreen",
    "No difference" = "gray60",
    "Worse"         = "firebrick"
  )) +
  
  geom_vline(xintercept = 0, linetype = "dashed") +
  
  facet_wrap(~ scenario) +
  
  labs(
    title = "Distribution of Net Crash Reduction (Δ) Across Scenarios",
    subtitle = "Positive values indicate fewer crashes under treatment",
    x = "Δ = Baseline − Treatment (10-year crashes)",
    y = "Probability"
  ) +
  
  theme_minimal() +
  theme(legend.title = element_blank())

p <- p +
  geom_text(
    data = df_stats,
    aes(
      x = x_pos,
      y = Inf,
      label = paste0(
        "P(Δ > 0) = ", round(p_improve, 2), "\n",
        "P(Δ = 0) = ", round(p_same, 2), "\n",
        "P(Δ < 0) = ", round(p_worse, 2)
      )
    ),
    vjust = 1.1,
    hjust = -0.5,
    inherit.aes = FALSE
  )

ggsave(
  filename = "eda/plotting-results/accident-simulation.png",
  plot = p,
  width = 12,
  height = 7,
  dpi = 300,
  bg = "white"
)